In [1]:
import os
import sys
import pandas as pd

# ---- Settings ----
PROJECT_ROOT = r"D:\RUSL\Final Project\TTS\voicelk_ml"
INPUT_PATH = r"D:\RUSL\Final Project\TTS\voicelk_ml\data\prepared\speaker_01_cleaned.csv"
OUTPUT_PATH = r"D:\RUSL\Final Project\TTS\voicelk_ml\data\final\speaker_01_metadata.csv"

FILE_NAME_COL = 0   # 1st column: file name
SPEAKER_COL = 1     # 2nd column: speaker id
TEXT_COL = 2        # 3rd column: text

sys.path.insert(0, os.path.join(PROJECT_ROOT, "model_engine"))
from pipeline import TextProcessingPipeline

# ---- Load (no header row) ----
if INPUT_PATH.lower().endswith((".xlsx", ".xls")):
    df = pd.read_excel(INPUT_PATH, header=None, dtype=str)
else:
    df = pd.read_csv(INPUT_PATH, header=None, dtype=str, encoding="utf-8")

print(f"Rows: {len(df)}")

pipeline = TextProcessingPipeline()

# ---- Convert row by row ----
records, errors = [], []

for idx, row in df.iterrows():
    file_name = str(row.iloc[FILE_NAME_COL]).strip()
    speaker_id = str(row.iloc[SPEAKER_COL]).strip()
    text = row.iloc[TEXT_COL]

    if pd.isna(text) or not str(text).strip():
        records.append([file_name, speaker_id, "", ""])
        continue

    try:
        result = pipeline.process(str(text).strip())
        records.append([file_name, speaker_id, result["normalized_text"], result["ipa_sequence"]])
    except Exception as e:
        records.append([file_name, speaker_id, "", ""])
        errors.append((idx, str(e)))

    if (idx + 1) % 100 == 0:
        print(f"Processed {idx + 1} rows...")

# ---- Output DataFrame: file_name, speaker_id, normalized_text, ipa_sequence ----
out_df = pd.DataFrame(records, columns=["file_name", "speaker_id", "normalized_text", "ipa_sequence"])

print(f"\nDone. Errors: {len(errors)}")
for idx, msg in errors[:20]:
    print(f"  row {idx}: {msg}")

# Save without header and without index
out_df.to_csv(OUTPUT_PATH, index=False, header=False, encoding="utf-8")
print(f"Saved to {OUTPUT_PATH}")

out_df.head()

Rows: 4139
Processed 100 rows...
Processed 200 rows...
Processed 300 rows...
Processed 400 rows...
Processed 500 rows...
Processed 600 rows...
Processed 700 rows...
Processed 800 rows...
Processed 900 rows...
Processed 1000 rows...
Processed 1100 rows...
Processed 1200 rows...
Processed 1300 rows...
Processed 1400 rows...
Processed 1500 rows...
Processed 1600 rows...
Processed 1700 rows...
Processed 1800 rows...
Processed 1900 rows...
Processed 2000 rows...
Processed 2100 rows...
Processed 2200 rows...
Processed 2300 rows...
Processed 2400 rows...
Processed 2500 rows...
Processed 2600 rows...
Processed 2700 rows...
Processed 2800 rows...
Processed 2900 rows...
Processed 3000 rows...
Processed 3100 rows...
Processed 3200 rows...
Processed 3300 rows...
Processed 3400 rows...
Processed 3500 rows...
Processed 3600 rows...
Processed 3700 rows...
Processed 3800 rows...
Processed 3900 rows...
Processed 4000 rows...
Processed 4100 rows...

Done. Errors: 0
Saved to D:\RUSL\Final Project\TTS\voicelk_ml\data\final\speaker_01_metadata.csv

,file_name,speaker_id,normalized_text,ipa_sequence
0,sin_s1_0001,1,සියලු දෙනාම සාදරයෙන් පිළිගන්නවා මේ Flutter cou...,sijəlu d̪enaːmə saːd̪ərəjen piɭigannəʋaː meː ˈ...
1,sin_s1_0002,1,"සරලවම කියනවනම් අපිට Android වලට , iOS වලට , Ma...","sarələʋəmə kijənəʋənam apiʈə ˈændrɔɪd ʋaləʈə ,..."
2,sin_s1_0003,1,වලට පවා එක code එකක් ලියලා apps ගොඩක් generate...,ʋaləʈə paʋaː ekə koʊd ekak lijəlaː æps goɖak ˈ...
3,sin_s1_0004,1,"මුල ඉඳන් Flutter කියන්නේ මොකක්ද , Dart කියන්නේ...","mulə ind̪an ˈflətər kijanneː mokakd̪ə , dɑrt k..."
4,sin_s1_0005,1,"ඊළඟට Flutter වලට ඕන කරන design patterns ගැන , ...",iːɭəŋgəʈə ˈflətər ʋaləʈə oːnə karənə dɪˈzaɪn ˈ...

In [2]:
import os
import sys
import pandas as pd

# ---- Settings ----
PROJECT_ROOT = r"D:\RUSL\Final Project\TTS\voicelk_ml"
INPUT_PATH = r"D:\RUSL\Final Project\TTS\voicelk_ml\data\prepared\speaker_02_cleaned.csv"
OUTPUT_PATH = r"D:\RUSL\Final Project\TTS\voicelk_ml\data\final\speaker_02_metadata.csv"

FILE_NAME_COL = 0   # 1st column: file name
SPEAKER_COL = 1     # 2nd column: speaker id
TEXT_COL = 2        # 3rd column: text

sys.path.insert(0, os.path.join(PROJECT_ROOT, "model_engine"))
from pipeline import TextProcessingPipeline

# ---- Load (no header row) ----
if INPUT_PATH.lower().endswith((".xlsx", ".xls")):
    df = pd.read_excel(INPUT_PATH, header=None, dtype=str)
else:
    df = pd.read_csv(INPUT_PATH, header=None, dtype=str, encoding="utf-8")

print(f"Rows: {len(df)}")

pipeline = TextProcessingPipeline()

# ---- Convert row by row ----
records, errors = [], []

for idx, row in df.iterrows():
    file_name = str(row.iloc[FILE_NAME_COL]).strip()
    speaker_id = str(row.iloc[SPEAKER_COL]).strip()
    text = row.iloc[TEXT_COL]

    if pd.isna(text) or not str(text).strip():
        records.append([file_name, speaker_id, "", ""])
        continue

    try:
        result = pipeline.process(str(text).strip())
        records.append([file_name, speaker_id, result["normalized_text"], result["ipa_sequence"]])
    except Exception as e:
        records.append([file_name, speaker_id, "", ""])
        errors.append((idx, str(e)))

    if (idx + 1) % 100 == 0:
        print(f"Processed {idx + 1} rows...")

# ---- Output DataFrame: file_name, speaker_id, normalized_text, ipa_sequence ----
out_df = pd.DataFrame(records, columns=["file_name", "speaker_id", "normalized_text", "ipa_sequence"])

print(f"\nDone. Errors: {len(errors)}")
for idx, msg in errors[:20]:
    print(f"  row {idx}: {msg}")

# Save without header and without index
out_df.to_csv(OUTPUT_PATH, index=False, header=False, encoding="utf-8")
print(f"Saved to {OUTPUT_PATH}")

out_df.head()

Rows: 3116
Processed 100 rows...
Processed 200 rows...
Processed 300 rows...
Processed 400 rows...
Processed 500 rows...
Processed 600 rows...
Processed 700 rows...
Processed 800 rows...
Processed 900 rows...
Processed 1000 rows...
Processed 1100 rows...
Processed 1200 rows...
Processed 1300 rows...
Processed 1400 rows...
Processed 1500 rows...
Processed 1600 rows...
Processed 1700 rows...
Processed 1800 rows...
Processed 1900 rows...
Processed 2000 rows...
Processed 2100 rows...
Processed 2200 rows...
Processed 2300 rows...
Processed 2400 rows...
Processed 2500 rows...
Processed 2600 rows...
Processed 2700 rows...
Processed 2800 rows...
Processed 2900 rows...
Processed 3000 rows...
Processed 3100 rows...

Done. Errors: 0
Saved to D:\RUSL\Final Project\TTS\voicelk_ml\data\final\speaker_02_metadata.csv

,file_name,speaker_id,normalized_text,ipa_sequence
0,sin_s2_0001,2,මෙන්න මේ app එකෙන් ඔයාටත් මෙන්න මේ වගේ dynamic...,mennə meː æp eken ojaːʈat̪ mennə meː ʋageː daɪ...
1,sin_s2_0002,2,ඒ වගේම මෙහෙම වුනත් කරන්න පුළුවන් . අද video එක...,eː ʋageːmə mehemə ʋunat̪ karannə puɭuʋan . ad̪...
2,sin_s2_0003,2,app එකේ නම තමා depth wallpapers . ඔයාට මේ වගේ ...,æp ekeː namə t̪amaː dɛpθ ˈwɔlˌpeɪpərz . ojaːʈə...
3,sin_s2_0004,2,තව ගොඩක් categories තියෙනවා . Cool ම part එක ත...,t̪aʋə goɖak ˈkætəˌgɔriz t̪ijenəʋaː . kul ma pɑ...
4,sin_s2_0005,2,widgets ඔයාගේ home screen එකේ set කරන්න පුළුවන...,ˈwɪdʒɪts ojaːgeː hoʊm skrin ekeː sɛt karannə p...

In [3]:
import os
import sys
import pandas as pd

# ---- Settings ----
PROJECT_ROOT = r"D:\RUSL\Final Project\TTS\voicelk_ml"
INPUT_PATH = r"D:\RUSL\Final Project\TTS\voicelk_ml\data\prepared\pathnirwana_cleaned.csv"
OUTPUT_PATH = r"D:\RUSL\Final Project\TTS\voicelk_ml\data\final\pathnirwana_metadata.csv"

FILE_NAME_COL = 0   # 1st column: file name
SPEAKER_COL = 1     # 2nd column: speaker id
TEXT_COL = 2        # 3rd column: text

sys.path.insert(0, os.path.join(PROJECT_ROOT, "model_engine"))
from pipeline import TextProcessingPipeline

# ---- Load (no header row) ----
if INPUT_PATH.lower().endswith((".xlsx", ".xls")):
    df = pd.read_excel(INPUT_PATH, header=None, dtype=str)
else:
    df = pd.read_csv(INPUT_PATH, header=None, dtype=str, encoding="utf-8")

print(f"Rows: {len(df)}")

pipeline = TextProcessingPipeline()

# ---- Convert row by row ----
records, errors = [], []

for idx, row in df.iterrows():
    file_name = str(row.iloc[FILE_NAME_COL]).strip()
    speaker_id = str(row.iloc[SPEAKER_COL]).strip()
    text = row.iloc[TEXT_COL]

    if pd.isna(text) or not str(text).strip():
        records.append([file_name, speaker_id, "", ""])
        continue

    try:
        result = pipeline.process(str(text).strip())
        records.append([file_name, speaker_id, result["normalized_text"], result["ipa_sequence"]])
    except Exception as e:
        records.append([file_name, speaker_id, "", ""])
        errors.append((idx, str(e)))

    if (idx + 1) % 100 == 0:
        print(f"Processed {idx + 1} rows...")

# ---- Output DataFrame: file_name, speaker_id, normalized_text, ipa_sequence ----
out_df = pd.DataFrame(records, columns=["file_name", "speaker_id", "normalized_text", "ipa_sequence"])

print(f"\nDone. Errors: {len(errors)}")
for idx, msg in errors[:20]:
    print(f"  row {idx}: {msg}")

# Save without header and without index
out_df.to_csv(OUTPUT_PATH, index=False, header=False, encoding="utf-8")
print(f"Saved to {OUTPUT_PATH}")

out_df.head()

Rows: 3300
Processed 100 rows...
Processed 200 rows...
Processed 300 rows...
Processed 400 rows...
Processed 500 rows...
Processed 600 rows...
Processed 700 rows...
Processed 800 rows...
Processed 900 rows...
Processed 1000 rows...
Processed 1100 rows...
Processed 1200 rows...
Processed 1300 rows...
Processed 1400 rows...
Processed 1500 rows...
Processed 1600 rows...
Processed 1700 rows...
Processed 1800 rows...
Processed 1900 rows...
Processed 2000 rows...
Processed 2100 rows...
Processed 2200 rows...
Processed 2300 rows...
Processed 2400 rows...
Processed 2500 rows...
Processed 2600 rows...
Processed 2700 rows...
Processed 2800 rows...
Processed 2900 rows...
Processed 3000 rows...
Processed 3100 rows...
Processed 3200 rows...
Processed 3300 rows...

Done. Errors: 0
Saved to D:\RUSL\Final Project\TTS\voicelk_ml\data\final\pathnirwana_metadata.csv

,file_name,speaker_id,normalized_text,ipa_sequence
0,sin_01_00001,0,කුඹුර ගොවියාට වී ලබා ගැනීමට උපකාරී වීම් වශයෙන්...,kumburə goʋijaːʈə ʋiː labaː gæniːməʈə upəkaːri...
1,sin_01_00002,0,එහෙත් ගොවියා වී ලබා ගනුයේ ඔහුගේ මහත් වූ වීර්ය්...,ehet̪ goʋijaː ʋiː labaː ganujeː ohugeː mahat̪ ...
2,sin_01_00003,0,ගොවියා ගේ ප්රයෝජනය පිණිස අල්ප ව්යායාමයකුදු කුඹ...,goʋijaː geː prajoːdʒənəjə piɳisə alpə ʋjaːjaːm...
3,sin_01_00004,0,එහෙත් කුඹුර නැතිව කොතෙක් උත්සාහ කළත් ගොවියාට ව...,ehet̪ kumburə næt̪iʋə kot̪ek ut̪saːhə kaɭat̪ g...
4,sin_01_00005,0,මනුෂ්යයන් විසින් කුඹුර වටිනා දෙයක් ලෙස පිළිගන්...,manuʃjəjan ʋisin kumburə ʋaʈinaː d̪ejak lesə p...